# Generated by Django 3.2.3 on 2021-08-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
